web:
  build: .
  command: 'bash -c ''node server.js'''
  working_dir: /app/user
  environment:
    PORT: 4567
  ports:
    - '4567:4567'
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 4567
  ports:
    - '4567:4567'
  volumes:
    - '.:/app/user'
